---
title: "History"
bibliography: references.bib
editor_options: 
  chunk_output_type: console
---


The spruce budworm atmospheric transport model (SBW-ATM) emerged from early US–Canada collaboration focused on understanding outbreak spread across shared forest landscapes.
Beginning in 2005, U.S. Department of Agriculture (USDA) Forest Service researcher Brian Sturtevant, Canadian Forest Service scientist Barry Cooke, and university partners from Quebec and Wisconsin began investigating spruce budworm dynamics in the "Border Lakes" region of Minnesota and Ontario—work that would seed the development of several tools, including the SBW-ATM.
Drawing on foundational aerobiology studies ([@Rainey1976],[&Sanders1978],[@greenbank1980]) and meteorological modelling by Gary Achtemeier, the model was grounded in particle dispersal principles and validated using trap captures from areas far removed from known outbreak centres [@scott1987; @achtemeier1998; @achtemeier2002].
First developed as an experimental tool in 2010, the model [@sturtevant2013] gained new urgency as a major outbreak emerged along Quebec’s north shore.
Following a 2014 international spruce budworm meeting hosted by the Canada–US Forest Health Initiative, development was expanded through a partnership between the USDA Forest Service, Canadian Forest Service (CFS), and the University of Wisconsin (UW).
CFS integrated the model into its BioSIM forecasting platform, while UW built a high-resolution Python version to leverage cloud computing and simulate millions of moth flight paths at finer spatial and temporal resolution.
Weather surveillance radar played a critical role in advancing the model's capabilities, confirming the presence of high-altitude mass exodus flights far beyond what earlier modelling functions predicted.
In response, CFS scientist Jacques Régnière mined archived datasets to develop biophysically grounded flight behaviours, enabling flight altitude and initiation to emerge from meteorological conditions rather than being hardcoded.
These additions dramatically improved the realism and adaptability of the model across diverse outbreak scenarios.
The CFS version supports strategic policy and outbreak planning, while UW’s experimental model helps guide tactical management decisions.
Both simulate realistic flight behaviours and “atmospheric rivers” of moths, incorporating real-time environmental inputs.
Today, SBW-ATM serves as an operational forecasting and backcasting tool that continues to evolve in both scope and scientific fidelity.

For more information on supporting publications, see [Publications](publications.qmd).

For more information on partnerships, see [About](about.qmd).

## References

<!-- bibliography is automatically generated; do not edit by hand -->

::: {#refs}
:::
