on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install additional system dependencies
        run: |
          sudo apt-get update -y && sudo apt-get install -y libmagick++-dev

      - name: Install R dependencies
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.3'

      - name: Setup renv
        uses: r-lib/actions/setup-renv@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.4.0
        with:
          workload_identity_provider: 'projects/919316026151/locations/global/workloadIdentityPools/github-actions/providers/github-actions'
          service_account: 'github-actions@sbw-atm-website.iam.gserviceaccount.com'

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
