on:
  push:
    branches: main
  schedule:
    - cron: "45 15 * * *" 
  workflow_dispatch:

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install and configure image magick
        ## increase the resource limits for the image pixel cache
        run: |
          sudo apt-get update -y && sudo apt-get install -y libmagick++-dev imagemagick
          sudo sed -i 's/\(<policy[^>]*name="memory"[^>]*value="\)[^"]*/\12GiB/' /etc/ImageMagick-6/policy.xml
          sudo sed -i 's/\(<policy[^>]*name="map"[^>]*value="\)[^"]*/\14GiB/' /etc/ImageMagick-6/policy.xml
          sudo sed -i 's/\(<policy[^>]*name="disk"[^>]*value="\)[^"]*/\15GiB/' /etc/ImageMagick-6/policy.xml

      - name: Install R dependencies
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.3'

      - name: Setup renv
        uses: r-lib/actions/setup-renv@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2.1.10
        with:
          credentials_json: '${{ secrets.GOOGLE_AUTH }}'

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          GOOGLE_AUTH: '${{ secrets.GOOGLE_AUTH }}'
